#!/usr/bin/env bash

set -eux

# Choose a Python to install conan
export PYBIN=/opt/python/cp310-cp310/bin

${PYBIN}/pip install conan

export CONAN_CMD=${PYBIN}/conan

cd /tket-conan-index

${CONAN_CMD} profile detect
DEFAULT_PROFILE_PATH=`${CONAN_CMD} profile path default`
PROFILE_PATH=./profiles/${CONAN_PROFILE}
diff ${DEFAULT_PROFILE_PATH} ${PROFILE_PATH} || true
cp ${PROFILE_PATH} ${DEFAULT_PROFILE_PATH}
${CONAN_CMD} remote add tket-libs https://quantinuumsw.jfrog.io/artifactory/api/conan/tket1-libs --index 0

for recipe in "$@"
do
    recipe_ver=$(conan inspect recipes/pybind11 | grep "^version: " | awk '{print $2}')
    echo "Installing ${recipe} ${recipe_ver} ..."
    ${CONAN_CMD} create recipes/${recipe} --user=tket --channel=stable --build=missing
    echo "Uploading ${recipe} ${recipe_ver} ..."
    ${CONAN_CMD} upload ${recipe}/${recipe_ver}@tket/stable -r=tket-libs
done

echo "Done."
