#!/usr/bin/env bash

set -eux

for recipe in "$@"
do
    recipe_ver=$(conan inspect recipes/${recipe} | grep "^version: " | awk '{print $2}')
    for build_type in Release Debug
    do
        echo "Installing ${recipe} ${recipe_ver} (${build_type}) ..."
        conan create recipes/${recipe} --user=tket --channel=stable --build=missing --settings build_type=${build_type}
    done
    echo "Uploading ${recipe} ${recipe_ver} ..."
    conan upload ${recipe}/${recipe_ver}@tket/stable -r=tket-libs
done

echo "Done."
